cube: product_analytics
description: "商品分析指标 - 销量、收入、利润"

dimensions:
  - name: category
    description: "商品类别"
    column: "products.category"

  - name: product_name
    description: "商品名称"
    column: "products.name"

  - name: order_time
    description: "订单时间"
    column: "orders.created_at"
    join: |
      JOIN order_items ON products.id = order_items.product_id
      JOIN orders ON order_items.order_id = orders.id
    granularity:
      - day:
          sql: "DATE(orders.created_at)"
          description: "按天"
      - month:
          sql: "DATE_TRUNC('month', orders.created_at)"
          description: "按月"

metrics:
  - name: total_products
    description: "商品总数"
    sql: "COUNT(DISTINCT products.id)"
    type: count

  - name: products_sold
    description: "已售商品数量"
    sql: |
      SUM(CASE WHEN orders.status IN ('paid', 'shipped', 'completed') THEN order_items.quantity ELSE 0 END)
    type: sum
    join: |
      LEFT JOIN order_items ON products.id = order_items.product_id
      LEFT JOIN orders ON order_items.order_id = orders.id

  - name: product_revenue
    description: "商品销售收入"
    sql: |
      SUM(CASE WHEN orders.status IN ('paid', 'shipped', 'completed') THEN order_items.subtotal ELSE 0 END)
    type: sum
    unit: "元"
    join: |
      LEFT JOIN order_items ON products.id = order_items.product_id
      LEFT JOIN orders ON order_items.order_id = orders.id

  - name: product_profit
    description: "商品利润 = 销售收入 - 成本"
    sql: |
      SUM(CASE WHEN orders.status IN ('paid', 'shipped', 'completed') 
        THEN order_items.subtotal - (products.cost * order_items.quantity) 
        ELSE 0 END)
    type: sum
    unit: "元"
    join: |
      LEFT JOIN order_items ON products.id = order_items.product_id
      LEFT JOIN orders ON order_items.order_id = orders.id

  - name: profit_margin
    description: "利润率"
    sql: |
      CASE 
        WHEN SUM(CASE WHEN orders.status IN ('paid', 'shipped', 'completed') THEN order_items.subtotal ELSE 0 END) > 0
        THEN (
          SUM(CASE WHEN orders.status IN ('paid', 'shipped', 'completed') 
            THEN order_items.subtotal - (products.cost * order_items.quantity) 
            ELSE 0 END)::DECIMAL /
          SUM(CASE WHEN orders.status IN ('paid', 'shipped', 'completed') THEN order_items.subtotal ELSE 0 END)
        ) * 100
        ELSE 0
      END
    type: percentage
    unit: "%"
    join: |
      LEFT JOIN order_items ON products.id = order_items.product_id
      LEFT JOIN orders ON order_items.order_id = orders.id

  - name: avg_unit_price
    description: "平均单价"
    sql: "AVG(products.price)"
    type: avg
    unit: "元"

filters:
  - name: active_products
    sql: "products.status = 'active'"
    description: "仅在售商品"

  - name: electronics
    sql: "products.category = '电子产品'"
    description: "电子产品类别"

  - name: clothing
    sql: "products.category = '服装'"
    description: "服装类别"
